// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Comany.Database.Access.Entities
{
    public partial class CustOrderHistResult
    {
        public string ProductName { get; set; } = default!;
        public int? Total { get; set; }
    }
}
