// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Comany.Database.Access.Entities
{
    public partial class TenMostExpensiveProductsResult
    {
        public string TenMostExpensiveProducts { get; set; } = default!;
        public decimal? UnitPrice { get; set; }
    }
}
