// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Company.Database.Access.Contexts;
using Company.Database.Access.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Company.Database.Access.Contexts.Configurations
{
    public partial class ProductSalesFor1997Configuration : IEntityTypeConfiguration<ProductSalesFor1997>
    {
        public void Configure(EntityTypeBuilder<ProductSalesFor1997> entity)
        {
            entity.ToView("Product Sales for 1997");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductSalesFor1997> entity);
    }
}
